
#ifndef STATICS_H
#define STATICS_H

int SCREEN_WIDTH = 1120;
int SCREEN_HEIGHT = 840;
//                           {x, y}
int SCREEN_START[2] = {0, 0};
int SCREEN_END[2] = {59, 59};
int SCREEN_CENTER[2] = {(SCREEN_END[0] - SCREEN_START[0]) / 2, (SCREEN_END[1] - SCREEN_START[1]) / 2};
int SCREEN_RADIUS = 30;
int FOV_RADIUS = 5;

int TILE_SIZE = 14;

int LOG_LINE_LENGTH = 18;
int LOG_LINE_COUNT = 18;
int LOG_LOWER_LEFT[2] = {61, 58};

int UPPER_CHAR_START = 0;
int LOWER_CHAR_START = 364;

int DARK_SPRITE_Y_START = 56;
int LIGHT_SPRITE_Y_START = 70;

int WALL_SPRITE_OFFSET = 0;
int FLOOR_SPRITE_OFFSET = 14;
int DOOR_SPRITE_OFFSET = 28;

int TOWER_HEIGHT = 6;

#endif
